// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum VpnStatus {
  disconnecting,
  disconnected,
  connecting,
  connected;
}

enum PlatformPermissionKind {
  none,
  androidVpn,
  macosSystemExtension,
  appleVpn,
  androidLocalNetwork;
}

enum PlatformPermissionState {
  notRequired,
  notDetermined,
  awaitingUserApproval,
  granted,
  denied,
  failed;
}

enum NativeVpnCommandState {
  success,
  waitingForPlatformPermission,
  failed;
}

enum NativeLaunchAtLoginState {
  enabled,
  disabled,
  requiresApproval,
  unavailable,
  error;
}

class AndroidAutomationSettings {
  AndroidAutomationSettings({
    required this.enabled,
    this.token,
  });

  bool enabled;

  String? token;

  List<Object?> _toList() {
    return <Object?>[
      enabled,
      token,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAutomationSettings decode(Object result) {
    result as List<Object?>;
    return AndroidAutomationSettings(
      enabled: result[0]! as bool,
      token: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAutomationSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(enabled, other.enabled) && _deepEquals(token, other.token);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAutomationSettings(enabled: $enabled, token: $token)';
  }
}

class BackupLocation {
  BackupLocation({
    required this.identifier,
    required this.label,
  });

  String identifier;

  String label;

  List<Object?> _toList() {
    return <Object?>[
      identifier,
      label,
    ];
  }

  Object encode() {
    return _toList();  }

  static BackupLocation decode(Object result) {
    result as List<Object?>;
    return BackupLocation(
      identifier: result[0]! as String,
      label: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BackupLocation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(identifier, other.identifier) && _deepEquals(label, other.label);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BackupLocation(identifier: $identifier, label: $label)';
  }
}

class AppleVpnCapabilities {
  AppleVpnCapabilities({
    required this.serviceExclusions,
    required this.deviceCommunication,
  });

  bool serviceExclusions;

  bool deviceCommunication;

  List<Object?> _toList() {
    return <Object?>[
      serviceExclusions,
      deviceCommunication,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleVpnCapabilities decode(Object result) {
    result as List<Object?>;
    return AppleVpnCapabilities(
      serviceExclusions: result[0]! as bool,
      deviceCommunication: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleVpnCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(serviceExclusions, other.serviceExclusions) && _deepEquals(deviceCommunication, other.deviceCommunication);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleVpnCapabilities(serviceExclusions: $serviceExclusions, deviceCommunication: $deviceCommunication)';
  }
}

class NativeLaunchAtLoginResult {
  NativeLaunchAtLoginResult({
    required this.state,
    this.message,
  });

  NativeLaunchAtLoginState state;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      state,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeLaunchAtLoginResult decode(Object result) {
    result as List<Object?>;
    return NativeLaunchAtLoginResult(
      state: result[0]! as NativeLaunchAtLoginState,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLaunchAtLoginResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLaunchAtLoginResult(state: $state, message: $message)';
  }
}

class PlatformPermissionResult {
  PlatformPermissionResult({
    required this.kind,
    required this.state,
    this.message,
  });

  PlatformPermissionKind kind;

  PlatformPermissionState state;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      state,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformPermissionResult decode(Object result) {
    result as List<Object?>;
    return PlatformPermissionResult(
      kind: result[0]! as PlatformPermissionKind,
      state: result[1]! as PlatformPermissionState,
      message: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPermissionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(state, other.state) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPermissionResult(kind: $kind, state: $state, message: $message)';
  }
}

class NativeVpnCommandResult {
  NativeVpnCommandResult({
    required this.state,
    this.status,
    this.permission,
    this.message,
  });

  NativeVpnCommandState state;

  VpnStatus? status;

  PlatformPermissionResult? permission;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      state,
      status,
      permission,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeVpnCommandResult decode(Object result) {
    result as List<Object?>;
    return NativeVpnCommandResult(
      state: result[0]! as NativeVpnCommandState,
      status: result[1] as VpnStatus?,
      permission: result[2] as PlatformPermissionResult?,
      message: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeVpnCommandResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(status, other.status) && _deepEquals(permission, other.permission) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeVpnCommandResult(state: $state, status: $status, permission: $permission, message: $message)';
  }
}

class AndroidAppInfo {
  AndroidAppInfo({
    required this.name,
    required this.packageName,
  });

  String name;

  String packageName;

  List<Object?> _toList() {
    return <Object?>[
      name,
      packageName,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAppInfo decode(Object result) {
    result as List<Object?>;
    return AndroidAppInfo(
      name: result[0]! as String,
      packageName: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAppInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(packageName, other.packageName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAppInfo(name: $name, packageName: $packageName)';
  }
}

/// One server row for the macOS menu bar. Display and latency are resolved in
/// the service layer so the native menu never parses node data itself.
class MenuServerItem {
  MenuServerItem({
    required this.id,
    required this.remark,
    required this.isCurrent,
    this.delay,
  });

  String id;

  String remark;

  bool isCurrent;

  /// Last measured latency in milliseconds, or null when it has never been
  /// measured or the measurement failed.
  int? delay;

  List<Object?> _toList() {
    return <Object?>[
      id,
      remark,
      isCurrent,
      delay,
    ];
  }

  Object encode() {
    return _toList();  }

  static MenuServerItem decode(Object result) {
    result as List<Object?>;
    return MenuServerItem(
      id: result[0]! as String,
      remark: result[1]! as String,
      isCurrent: result[2]! as bool,
      delay: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MenuServerItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(remark, other.remark) && _deepEquals(isCurrent, other.isCurrent) && _deepEquals(delay, other.delay);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MenuServerItem(id: $id, remark: $remark, isCurrent: $isCurrent, delay: $delay)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VpnStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformPermissionKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformPermissionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is NativeVpnCommandState) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is NativeLaunchAtLoginState) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is AndroidAutomationSettings) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is BackupLocation) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is AppleVpnCapabilities) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is NativeLaunchAtLoginResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformPermissionResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is NativeVpnCommandResult) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidAppInfo) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is MenuServerItem) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformPermissionKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformPermissionState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeVpnCommandState.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeLaunchAtLoginState.values[value];
      case 134:
        return AndroidAutomationSettings.decode(readValue(buffer)!);
      case 135:
        return BackupLocation.decode(readValue(buffer)!);
      case 136:
        return AppleVpnCapabilities.decode(readValue(buffer)!);
      case 137:
        return NativeLaunchAtLoginResult.decode(readValue(buffer)!);
      case 138:
        return PlatformPermissionResult.decode(readValue(buffer)!);
      case 139:
        return NativeVpnCommandResult.decode(readValue(buffer)!);
      case 140:
        return AndroidAppInfo.decode(readValue(buffer)!);
      case 141:
        return MenuServerItem.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BridgeHostApi {
  /// Constructor for [BridgeHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BridgeHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<String> getTunFilesDir() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.getTunFilesDir$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<NativeVpnCommandResult> readVpnStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.readVpnStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeVpnCommandResult;
  }

  Future<NativeVpnCommandResult> startVpn() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.startVpn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeVpnCommandResult;
  }

  Future<NativeVpnCommandResult> stopVpn() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.stopVpn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeVpnCommandResult;
  }

  Future<String> invoke(String requestJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.invoke$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<PlatformPermissionResult> queryPlatformPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.queryPlatformPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformPermissionResult;
  }

  Future<PlatformPermissionResult> requestPlatformPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.requestPlatformPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformPermissionResult;
  }

  Future<List<AndroidAppInfo>> getInstalledApps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.getInstalledApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<AndroidAppInfo>();
  }

  Future<Uint8List?> getAppIcon(String packageName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.getAppIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as Uint8List?;
  }

  Future<bool> useSystemExtension() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.useSystemExtension$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<AppleVpnCapabilities> appleVpnCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.appleVpnCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AppleVpnCapabilities;
  }

  Future<NativeLaunchAtLoginResult> queryLaunchAtLogin() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.queryLaunchAtLogin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeLaunchAtLoginResult;
  }

  Future<NativeLaunchAtLoginResult> setLaunchAtLogin(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.setLaunchAtLogin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeLaunchAtLoginResult;
  }

  Future<bool> openLaunchAtLoginSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.openLaunchAtLoginSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> setAppIcon(String appIcon) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.setAppIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[appIcon]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<String> getCurrentAppIcon() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BridgeHostApi.getCurrentAppIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }
}

class AndroidAutomationHostApi {
  /// Constructor for [AndroidAutomationHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AndroidAutomationHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<AndroidAutomationSettings> read() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.AndroidAutomationHostApi.read$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAutomationSettings;
  }

  Future<AndroidAutomationSettings> setEnabled(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.AndroidAutomationHostApi.setEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAutomationSettings;
  }

  Future<AndroidAutomationSettings> resetToken() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.AndroidAutomationHostApi.resetToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAutomationSettings;
  }

  Future<void> setStartBlocked(bool blocked) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.AndroidAutomationHostApi.setStartBlocked$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[blocked]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> clear() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.AndroidAutomationHostApi.clear$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

class BackupHostApi {
  /// Constructor for [BackupHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BackupHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<BackupLocation?> selectBackupFile(bool create) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BackupHostApi.selectBackupFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[create]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BackupLocation?;
  }

  Future<void> requireBackupAccess(String identifier) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BackupHostApi.requireBackupAccess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[identifier]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> releaseBackupFile(String identifier) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onexray.BackupHostApi.releaseBackupFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[identifier]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class BridgeFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> vpnStatusChanged(VpnStatus status);

  Future<List<MenuServerItem>> listMenuServers();

  Future<List<MenuServerItem>> speedTestMenuServers();

  Future<void> selectMenuServer(String id);

  static void setUp(BridgeFlutterApi? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.onexray.BridgeFlutterApi.vpnStatusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VpnStatus arg_status = args[0]! as VpnStatus;
          try {
            await api.vpnStatusChanged(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.onexray.BridgeFlutterApi.listMenuServers$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final List<MenuServerItem> output = await api.listMenuServers();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.onexray.BridgeFlutterApi.speedTestMenuServers$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final List<MenuServerItem> output = await api.speedTestMenuServers();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.onexray.BridgeFlutterApi.selectMenuServer$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_id = args[0]! as String;
          try {
            await api.selectMenuServer(arg_id);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
