skip_docs

default_platform :mac

def flutter_build_args(*args)
  ['flutter', 'build', *args]
end

platform :mac do
  lane :deploy do
    installer_cert_name = ENV.fetch('FASTLANE_MAS_INSTALLER_CERT')

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch('FASTLANE_ASC_KEY_ID'),
      issuer_id: ENV.fetch('FASTLANE_ASC_ISSUER_ID'),
      key_filepath: './fastlane/AuthKey.p8'
    )

    [
      ['ink.xcl.onexray', 'OneXraymacOS'],
      ['ink.xcl.onexray.tun', 'OneXraymacOSTun']
    ].each do |app_identifier, provisioning_name|
      get_provisioning_profile(
        api_key: api_key,
        app_identifier: app_identifier,
        provisioning_name: provisioning_name,
        ignore_profiles_with_different_name: true,
        platform: 'macos',
        readonly: true
      )
    end

    Dir.chdir('..') do
      sh(*flutter_build_args('macos'))
    end

    build_app(
        scheme: 'Runner',
        configuration: 'Release',
        output_directory: File.expand_path('../../../output', __dir__),
        export_options: {
          method: 'app-store-connect',
          provisioningProfiles: {
            'ink.xcl.onexray' => 'OneXraymacOS',
            'ink.xcl.onexray.tun' => 'OneXraymacOSTun'
          }
        },
        installer_cert_name: installer_cert_name
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
