skip_docs

default_platform :ios

def flutter_build_args(*args)
  ['flutter', 'build', *args]
end

platform :ios do
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch('FASTLANE_ASC_KEY_ID'),
      issuer_id: ENV.fetch('FASTLANE_ASC_ISSUER_ID'),
      key_filepath: './fastlane/AuthKey.p8'
    )

    [
      ['ink.xcl.onexray', 'OneXrayiOS'],
      ['ink.xcl.onexray.tun', 'OneXrayiOSTun']
    ].each do |app_identifier, provisioning_name|
      get_provisioning_profile(
        api_key: api_key,
        app_identifier: app_identifier,
        provisioning_name: provisioning_name,
        ignore_profiles_with_different_name: true,
        readonly: true
      )
    end

    Dir.chdir('..') do
      sh(*flutter_build_args('ipa'))
    end

    build_app(
        skip_build_archive: true,
        archive_path: "../build/ios/archive/Runner.xcarchive",
        output_directory: File.expand_path('../../../output', __dir__),
        output_name: 'OneXray-ios',
        export_options: {
          method: 'app-store-connect',
          provisioningProfiles: {
            'ink.xcl.onexray' => 'OneXrayiOS',
            'ink.xcl.onexray.tun' => 'OneXrayiOSTun'
          }
        })
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
